### ISSUE TITLE
Modifications to get ready for Numpy 2

### ISSUE THREAD

**Issue by mbakker7** [mbakker7/timml#111]
Some things will stop working in Numpy 2. 
May want to consider using ruff to get these changes implemented automatically. 
What flopy did:

switch to ruff from black, isort, flake8, pylint, keep (mostly) the same settings
apply some suggested linting/formatting rules, ignore others in pyproject.toml
run ruff check --select NPY201 as suggested [here](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin), replace deprecated syntax
np.float_ -> np.float64
np.NaN -> np.nan
.real and .imag will also stop working on numpy arrays it seems

**Comment by Huite** [comment]
I'm adding ruff in #114, using the NPY rules as well.

It always run NPY201, but doing so expliclitly:
```
❯ ruff check . --select NPY201
All checks passed!
```

As noted this morning, `.real` and `.imag` will still work on arrays, possibly not on numpy scalars.

Looks like timml is numpy2.0 proof!

(It was still good that I reverted the conda-forge feedstock though, because numpy 2.0 itself didn't seem quite stable yet.)

**Comment by mbakker7** [comment]
Fixed with release 6.5.0
